name: Build Android C++ Lib
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with ndk-build
        run: |
          $ANDROID_NDK_LATEST_HOME/ndk-build -C jni

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ghost_lib
          path: libs/